language: elixir

elixir: 1.7.4

otp_release: 21.0.9

services:
  - postgresql

branches:
  only:
    - master

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
